# Site settings
name: Dharanidhar Reddy Yerram
title: Dharanidhar | Software Engineer
description: software engineer focused on building innovative applications that make a difference.
url: https://dreddyyerram.github.io/
baseurl: ''
email: yerramdharanidhar@gmail.com
cover: https://dreddyyerram.github.io/img/og.png
logo: https://dreddyyerram.github.io/img/emojis/technologist.png
resume: https://dreddyyerram.github.io/resume.pdf
social:
  - title: email
    url: mailto:yerramdharanidhar@gmail.com
  - title: twitter
    url: https://twitter.com/bablooyerram
  - title: github
    url: https://github.com/dreddyyerram
  - title: linkedin
    url: https://www.linkedin.com/in/dharanidharreddy/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
